import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/core/auth/context/AuthContext";
import { ProjectProvider } from "@/core/projects/context/ProjectContext";
import { Toaster } from "sonner";
import { QueryProvider } from "@/infra/api/QueryProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-900 bg-slate-50`}>
        <QueryProvider>
          <AuthProvider>
            <ProjectProvider>
              {children}
              <Toaster position="top-right" richColors />
            </ProjectProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
